package net.cmr.easyauth.util;

import java.util.Base64;
import java.util.Map;

import javax.crypto.SecretKey;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.security.oauth2.resource.OAuth2ResourceServerProperties.Jwt;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import net.cmr.easyauth.entity.EALogin;

public class JwtUtil {
    
    @Value("{cmr.easyauth.enableAccessTokens:true}")
    public static boolean accessTokensEnabled;
    @Value("${net.cmr.easyauth.jwtSecretKey:AUTOGENERATE}")    
    private String secretKeyConfiguration;
    private static SecretKey secretKey;

    public static final Logger logger = LoggerFactory.getLogger(JwtUtil.class);
    
    @Autowired
    public void setSecret() {
        if (secretKeyConfiguration.equals("AUTOGENERATE")) {
            logger.info("Autogenerating JWT secret key...");
            secretKey = Keys.secretKeyFor(SignatureAlgorithm.HS256);
            String base64String = Base64.getEncoder().encodeToString(secretKey.getEncoded());
            logger.info("AUTOGENERATED KEY: " + base64String);
        } else {
            byte[] keyBytes = Base64.getDecoder().decode(secretKeyConfiguration);
            secretKey = Keys.hmacShaKeyFor(keyBytes);
            logger.info("Successfully loaded JWT secret key.");
        }
    }

    public static String signJwt(EALogin login, boolean accessToken) {
        return Jwts.builder()
            .signWith(secretKey)
            .setSubject(Boolean.toString(accessToken))
            .setId(login.getId().toString())
            .compact();
    }

    public static boolean isTokenType(String jwt, boolean accessToken) {
        return Boolean.valueOf(Jwts.parserBuilder()
            .setSigningKey(secretKey)
            .build()
            .parseClaimsJwt(jwt)
            .getBody()
            .getSubject()
            .toString());
    }

    public static long getId(String jwt) {
        return Long.valueOf(Jwts.parserBuilder()
            .setSigningKey(secretKey)
            .build()
            .parseClaimsJwt(jwt)
            .getBody()
            .getId());
    }

}
